#!/usr/bin/env python3
"""Generate native/dispatch.rs from spike/googlesql.wasm.

All exported RPC functions share the wasm signature (i32, i32) -> i64.
This script parses the wasm export + function-type sections (via
`wasm-tools print --skeleton`) and emits two generic dispatch functions:

  * packed_by_rpc(svc, mid)  -- one arm per export named `w_<svc>_<mid>`
  * packed_by_name(name)     -- one arm per non-w_ export whose name is not one
                                of the lifecycle/alloc funcs and whose type is
                                (i32, i32) -> i64.

Output path native/dispatch.rs is gitignored (regenerated, not committed).

Usage: python3 scripts/gen-native-dispatch.py
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WASM = REPO / "spike" / "googlesql.wasm"
OUT = REPO / "native" / "dispatch.rs"

# Names that are NOT dispatched via packed_by_name (lifecycle / allocator).
EXCLUDED_NAMES = {
    "_initialize",
    "wasm_alloc",
    "wasm_free",
    "wasm_init",
    "wasm_shutdown",
    "memory",  # not a func export
}

W_RE = re.compile(r'^\(export "w_(\d+)_(\d+)" \(func (\d+)\)\)$')
NAMED_RE = re.compile(r'^\(export "([^"]+)" \(func (\d+)\)\)$')
# type decl:  (type (;N;) (func (param ...) (result ...)))
TYPE_RE = re.compile(r'^\(type \(;(\d+);\) \(func(.*)\)\)$')
# func decl in skeleton: (func (;IDX;) (type T) (param ...) (result ...) ...)
FUNC_RE = re.compile(r'^\(func \(;(\d+);\) \(type (\d+)\)(.*)$')


def sig_from_body(body: str) -> tuple[list[str], list[str]]:
    """Extract (params, results) value-type lists from a wat func body fragment."""
    params: list[str] = []
    results: list[str] = []
    for m in re.finditer(r'\((param|result)([^()]*)\)', body):
        kind = m.group(1)
        types = m.group(2).split()
        if kind == "param":
            params.extend(types)
        else:
            results.extend(types)
    return params, results


def main() -> int:
    if not WASM.exists():
        print(f"error: {WASM} not found", file=sys.stderr)
        return 1

    skel = subprocess.run(
        ["wasm-tools", "print", "--skeleton", str(WASM)],
        check=True,
        capture_output=True,
        text=True,
    ).stdout

    type_sigs: dict[int, tuple[list[str], list[str]]] = {}
    func_type: dict[int, int] = {}
    w_arms: list[tuple[int, int, int]] = []  # (svc, mid, func_idx)
    named_exports: list[tuple[str, int]] = []  # (name, func_idx)

    for raw in skel.splitlines():
        line = raw.strip()

        mt = TYPE_RE.match(line)
        if mt:
            type_sigs[int(mt.group(1))] = sig_from_body(mt.group(2))
            continue

        mf = FUNC_RE.match(line)
        if mf:
            func_type[int(mf.group(1))] = int(mf.group(2))
            continue

        mw = W_RE.match(line)
        if mw:
            w_arms.append((int(mw.group(1)), int(mw.group(2)), int(mw.group(3))))
            continue

        mn = NAMED_RE.match(line)
        if mn:
            named_exports.append((mn.group(1), int(mn.group(2))))

    # Filter named exports to non-w_, non-excluded, signature (i32,i32)->i64.
    name_arms: list[tuple[str, int]] = []
    for name, idx in named_exports:
        if name.startswith("w_") and W_RE.match(f'(export "{name}" (func {idx}))'):
            continue
        if name in EXCLUDED_NAMES:
            continue
        t = func_type.get(idx)
        if t is None:
            print(f"warning: no type for func {idx} ({name})", file=sys.stderr)
            continue
        params, results = type_sigs.get(t, ([], []))
        if params == ["i32", "i32"] and results == ["i64"]:
            name_arms.append((name, idx))
        else:
            print(
                f"note: skipping named export {name} (func {idx}) "
                f"sig=({params})->({results})",
                file=sys.stderr,
            )

    w_arms.sort()
    name_arms.sort()

    lines: list[str] = []
    lines.append(
        "// @generated by scripts/gen-native-dispatch.py -- do not edit."
    )
    lines.append("// include!'d by the native backend shim.")
    lines.append("")
    lines.append("pub(crate) fn packed_by_rpc<H: guest::Imports>(")
    lines.append("    svc: i32,")
    lines.append("    mid: i32,")
    lines.append(") -> Option<fn(&mut guest::Instance<H>, i32, i32) -> i64> {")
    lines.append("    Some(match (svc, mid) {")
    for svc, mid, idx in w_arms:
        lines.append(
            f"        ({svc}, {mid}) => guest::Instance::<H>::func{idx},"
        )
    lines.append("        _ => return None,")
    lines.append("    })")
    lines.append("}")
    lines.append("")
    lines.append("pub(crate) fn packed_by_name<H: guest::Imports>(")
    lines.append("    name: &str,")
    lines.append(") -> Option<fn(&mut guest::Instance<H>, i32, i32) -> i64> {")
    lines.append("    Some(match name {")
    for name, idx in name_arms:
        lines.append(
            f'        "{name}" => guest::Instance::<H>::func{idx},'
        )
    lines.append("        _ => return None,")
    lines.append("    })")
    lines.append("}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))

    print(f"wrote {OUT}")
    print(f"packed_by_rpc arms: {len(w_arms)}")
    print(f"packed_by_name arms: {len(name_arms)}")
    for name, idx in name_arms:
        print(f"  {name} => func{idx}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
