//! The native [`GuestInstance`] engine: googlesql.wasm transpiled to standalone
//! Rust by wasm2rs and linked directly, with no wasm runtime.
//!
//! Enabled by the `native` feature. The generated crate `guest` (gitignored,
//! produced by `scripts/gen-native-guest.sh`) exposes `Instance<H: Imports>`
//! with one `func{N}` method per wasm function, addressed by function index.
//! This module supplies the host [`guest::Imports`] — the C++ runtime `env`
//! stubs the module leaves unresolved — and drives the `w_<svc>_<mid>(ptr,len)
//! -> packed` RPC exports through the generated dispatch in `native/dispatch.rs`.
//!
//! The stub semantics mirror the wasmtime backend's `env` stubs exactly: a C++
//! throw traps (here: panics), `wasmify::callback_invoke` returns 0, and every
//! other import returns the zero value of its result type. Keeping them
//! identical is what lets the differential tests expect byte-for-byte agreement.

// The native engine (and its generated dispatch) is currently reached only from
// the differential tests below — `Module::new_native` has no non-test caller
// yet. A public entry point is a later phase; until then these items are "unused"
// in a `--features native` lib build without `cfg(test)`.
#![allow(
    dead_code,
    reason = "native engine is exercised only by the differential tests for now; public API is a later phase"
)]

use crate::backend::GuestInstance;
use crate::error::Error;

// The generated (svc,mid)/name -> `Instance` method dispatch. `packed_by_rpc`
// and `packed_by_name` map an export to its `func{N}` as a function pointer;
// both are regenerated by scripts/gen-native-dispatch.py and gitignored. Wrapped
// in a module so the one blanket allow for the machine-generated table stays
// scoped to it.
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    reason = "machine-generated dispatch table (26k arms); not hand-maintained"
)]
mod dispatch {
    include!("../native/dispatch.rs");
}

/// Host imports the transpiled module leaves to us: the C++ runtime `env`
/// symbols plus two WASI functions wasm2rs did not wire natively.
///
/// Zero-sized: it carries no state. `alloc`/`free`/memory live on the
/// `Instance`, not here, so an import method cannot touch guest memory — the
/// `__cxa_allocate_exception` stub therefore returns 0 (a lossy pointer), which
/// is harmless because `__cxa_throw` traps before the guest can use it.
struct HostImports;

#[expect(
    clippy::panic,
    reason = "a C++ throw cannot be unwound through native Rust; trapping matches the wasmtime env stub"
)]
impl guest::Imports for HostImports {
    // `__cxa_throw`: terminate, mirroring the wasmtime stub that returns a trap.
    fn import2(&mut self, _a0: i32, _a1: i32, _a2: i32) {
        panic!("C++ exception thrown in wasm (env::__cxa_throw)");
    }

    // `wasmify::callback_invoke`: no callbacks are registered, so 0 = "no handler".
    fn import4(&mut self, _a0: i32, _a1: i32, _a2: i32, _a3: i32) -> i64 {
        0
    }

    // All remaining imports return the zero value of their result type, matching
    // the wasmtime `env` stubs (`__cxa_allocate_exception` included: 0).
    fn import0(&mut self, _a0: i32) -> i32 {
        0
    }
    fn import1(&mut self, _a0: i32) -> i32 {
        0
    }
    fn import3(&mut self, _a0: i32, _a1: i32, _a2: i32, _a3: i32, _a4: i32) {}
    fn import5(&mut self, _a0: i32, _a1: i32, _a2: i32) -> i32 {
        0
    }
    fn import6(&mut self, _a0: i32) -> i32 {
        0
    }
    fn import7(&mut self, _a0: i32, _a1: i32, _a2: i32) -> i32 {
        0
    }
    fn import8(&mut self) -> i32 {
        0
    }
    fn import9(&mut self) -> i32 {
        0
    }
    fn import10(&mut self) -> i32 {
        0
    }
    fn import11(&mut self) -> i32 {
        0
    }
    fn import12(&mut self, _a0: i32, _a1: i32, _a2: i32) -> i32 {
        0
    }
    fn import13(&mut self) -> i32 {
        0
    }
    fn import14(&mut self, _a0: i32) -> i32 {
        0
    }
    fn import15(&mut self, _a0: i32, _a1: i32) {}
    fn import16(&mut self, _a0: i32) -> i32 {
        0
    }
    fn import17(&mut self, _a0: i32) -> i32 {
        0
    }
    fn import18(&mut self, _a0: i32) -> i32 {
        0
    }
    fn import19(&mut self, _a0: i32, _a1: i32, _a2: i32, _a3: i32, _a4: i32) -> i32 {
        0
    }
    fn import20(&mut self, _a0: i32) {}
    fn import21(&mut self, _a0: i32, _a1: i32, _a2: i32, _a3: i32, _a4: i32, _a5: i32) -> i32 {
        0
    }
    fn import22(&mut self, _a0: i32) {}
    fn import23(&mut self, _a0: i32) -> i32 {
        0
    }
    fn import24(&mut self, _a0: i32) -> i32 {
        0
    }
    fn import25(&mut self, _a0: i32, _a1: i32, _a2: i32) -> i32 {
        0
    }
    // `fd_fdstat_set_flags`: report success.
    fn import31(&mut self, _a0: i32, _a1: i32) -> i32 {
        0
    }
    // `poll_oneoff`: report success.
    fn import38(&mut self, _a0: i32, _a1: i32, _a2: i32, _a3: i32) -> i32 {
        0
    }
}

/// A running instance of the wasm2rs-transpiled GoogleSQL guest.
///
/// Holds the generated `Instance` (which owns the guest's linear memory as a
/// `Vec<u8>`) and drives it entirely in native Rust. Like the wasmtime engine
/// it is single-threaded per instance; it is [`Send`] but not `Sync`.
pub struct NativeInstance {
    instance: guest::Instance<HostImports>,
}

impl NativeInstance {
    /// Constructs the guest and runs its two-stage initialization, matching the
    /// wasmtime backend: `_initialize` (func41, WASI-reactor / C++ global ctors)
    /// then `wasm_init` (func15885, whose returned status is ignored there too).
    ///
    /// The preopen root is "/" — the same read-only filesystem guarantee the
    /// wasmtime backend gives (it preopens "/"). The analyzer's `AnalyzerOptions`
    /// resolves a default timezone through absl cctz, which reads absolute paths
    /// under `/usr/share/zoneinfo` (and may consult `/etc/localtime`); rooting the
    /// single WASI preopen at "/" lets those absolute reads resolve, exactly as
    /// under wasmtime. Without it the guest traps when cctz's read is refused.
    pub(crate) fn new() -> Result<Self, Error> {
        let mut instance = guest::Instance::new(HostImports).with_preopen_root("/");
        instance.func41();
        let _status: i32 = instance.func15885();
        Ok(Self { instance })
    }
}

impl GuestInstance for NativeInstance {
    // `wasm_alloc` (func42) and `wasm_free` (func43): u32<->i32 is a pure
    // reinterpretation of the same 32 bits (guest pointers, not values), so
    // `cast_signed`/`cast_unsigned` are exact and avoid a lossy `as`.
    fn alloc(&mut self, len: u32) -> Result<u32, Error> {
        Ok(self.instance.func42(len.cast_signed()).cast_unsigned())
    }

    fn free(&mut self, ptr: u32) -> Result<(), Error> {
        self.instance.func43(ptr.cast_signed());
        Ok(())
    }

    fn write(&mut self, ptr: u32, data: &[u8]) -> Result<(), Error> {
        let offset = usize::try_from(ptr).map_err(|e| Error::Memory(e.to_string()))?;
        let end = offset
            .checked_add(data.len())
            .ok_or_else(|| Error::Memory("write range overflows usize".into()))?;
        let mem = self.instance.memory();
        let mem_len = mem.len();
        let dst = mem.get_mut(offset..end).ok_or_else(|| {
            Error::Memory(format!(
                "write {offset}..{end} out of bounds (memory len {mem_len})"
            ))
        })?;
        dst.copy_from_slice(data);
        Ok(())
    }

    fn read(&mut self, ptr: u32, len: u32) -> Result<Vec<u8>, Error> {
        let offset = usize::try_from(ptr).map_err(|e| Error::Memory(e.to_string()))?;
        let len = usize::try_from(len).map_err(|e| Error::Memory(e.to_string()))?;
        let end = offset
            .checked_add(len)
            .ok_or_else(|| Error::Memory("read range overflows usize".into()))?;
        let mem = self.instance.memory();
        let mem_len = mem.len();
        let slice = mem.get(offset..end).ok_or_else(|| {
            Error::Memory(format!(
                "read {offset}..{end} out of bounds (memory len {mem_len})"
            ))
        })?;
        Ok(slice.to_vec())
    }

    fn call_rpc(&mut self, svc: i32, mid: i32, req_ptr: u32, req_len: u32) -> Result<u64, Error> {
        let func = dispatch::packed_by_rpc::<HostImports>(svc, mid)
            .ok_or_else(|| Error::Wasm(format!("no native export `w_{svc}_{mid}`")))?;
        let packed = func(
            &mut self.instance,
            req_ptr.cast_signed(),
            req_len.cast_signed(),
        );
        Ok(packed.cast_unsigned())
    }

    fn call_named(&mut self, name: &str, req_ptr: u32, req_len: u32) -> Result<u64, Error> {
        let func = dispatch::packed_by_name::<HostImports>(name)
            .ok_or_else(|| Error::Wasm(format!("no native export `{name}`")))?;
        let packed = func(
            &mut self.instance,
            req_ptr.cast_signed(),
            req_len.cast_signed(),
        );
        Ok(packed.cast_unsigned())
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, reason = "test code")]
mod tests {
    use crate::Module;

    /// The differential gate for the native backend: for the same SQL, the
    /// native engine must produce byte-for-byte identical results to wasmtime.
    /// Parser and formatter are timezone-independent (they never construct
    /// `AnalyzerOptions`), so they exercise the full alloc/write/RPC/read/free
    /// path without the WASI zoneinfo dependency the analyzer needs.
    #[test]
    fn format_sql_matches_wasmtime() {
        let queries = [
            "select 1",
            "select 1+2 as x from t where a > 3",
            "SELECT a, b FROM t JOIN u ON t.id = u.id GROUP BY a HAVING count(*) > 1",
            "with q as (select 1 as n) select n from q",
        ];

        let mut wasmtime = Module::new().expect("wasmtime engine");
        let mut native = Module::new_native().expect("native engine");

        for sql in queries {
            let expected = wasmtime.format_sql(sql).expect("wasmtime format");
            let actual = native.format_sql(sql).expect("native format");
            assert_eq!(actual, expected, "format_sql mismatch for {sql:?}");
        }
    }

    #[test]
    fn parse_statement_matches_wasmtime() {
        let queries = [
            "select 1",
            "select a, b from t where a > 3 order by b limit 10",
            "select * from a union all select * from b",
        ];

        let mut wasmtime = Module::new().expect("wasmtime engine");
        let mut native = Module::new_native().expect("native engine");

        for sql in queries {
            let expected = wasmtime.parse_statement(sql).expect("wasmtime parse");
            let actual = native.parse_statement(sql).expect("native parse");
            assert_eq!(
                actual.canonical_sql(),
                expected.canonical_sql(),
                "canonical SQL mismatch for {sql:?}"
            );
        }
    }

    /// A syntax error must surface as an `Err` on the native engine too, not a
    /// panic or a spurious success.
    #[test]
    fn parse_error_matches_wasmtime() {
        let mut native = Module::new_native().expect("native engine");
        assert!(
            native.parse_statement("SELECT FROM").is_err(),
            "native engine must reject a syntax error"
        );
    }

    /// The analyzer exercises the timezone-dependent path: constructing
    /// `AnalyzerOptions` resolves a default timezone via absl cctz, which reads
    /// `/usr/share/zoneinfo`. The native WASI shim must expose that directory
    /// (via `with_preopen_root`) for this to work at all; without it the guest
    /// traps. For the same expression the inferred type must match wasmtime
    /// byte-for-byte.
    #[test]
    fn analyze_expression_matches_wasmtime() {
        let exprs = [
            "1 + 2",
            "cast('2024-01-01' as date)",
            "current_timestamp()",
            "timestamp('2024-01-01 00:00:00')",
            "struct(1 as a, 'x' as b)",
        ];

        let mut wasmtime = Module::new().expect("wasmtime engine");
        let mut native = Module::new_native().expect("native engine");

        for sql in exprs {
            let expected = wasmtime
                .analyze_expression(sql, &[])
                .expect("wasmtime analyze");
            let actual = native.analyze_expression(sql, &[]).expect("native analyze");
            assert_eq!(actual, expected, "analyzed type mismatch for {sql:?}");
        }
    }

    /// A full statement analysis (the default-catalog path) must agree on
    /// success too, not just expression typing.
    #[test]
    fn analyze_statement_matches_wasmtime() {
        let sql = "select 1 as a, current_timestamp() as t";

        let mut wasmtime = Module::new().expect("wasmtime engine");
        let mut native = Module::new_native().expect("native engine");

        let expected = wasmtime.analyze_statement(sql);
        let actual = native.analyze_statement(sql);
        assert_eq!(
            actual.is_ok(),
            expected.is_ok(),
            "analyze_statement success mismatch for {sql:?}"
        );
    }
}
